### PR TITLE
Add internals exposed in 716198d to the packaged js

### PR DESCRIPTION
**Pull request by cbeer**
I believe this will match the intent behind 716198d; currently, some of those newly "exposed" internals are just returning `undefined`.

### CODE REVIEW

**Comment by edsilv** [comment]
This should be solved in #46 by exporting everything from index.ts: https://github.com/IIIF-Commons/manifesto/blob/e73f86fd4234eb0cfa682902a4182e7649d5420e/src/index.ts

**Comment by cbeer** [comment]
Ok, and you think that'll get merged and released relatively soon?

**Comment by edsilv** [comment]
This is the blocker: https://github.com/IIIF-Commons/manifesto/pull/46#discussion_r299081687
I'm working on a community sprint right now, but the emphasis is on fixing the UV's tree component. If I have any time left next week I'll see if I can address this remaining problem with manifesto.
Note that Stanford, Harvard, and Princeton are also able to merge and release code on IIIF Commons :-)

**Comment by mejackreed** [comment]
@edsilv WRT 

> Note that Stanford, Harvard, and Princeton are also able to merge and release code on IIIF Commons :-)

Is there some process where that is setup? I don't seem to have permissions on GitHub or npmjs.com.

Who are the owners of IIIF-Commons who could grant our team that?

**Comment by edsilv** [comment]
@mejackreed Drew, Rashmi, Shaun, and I have been owners since it was set up. Have sent you an invite.

**Comment by mejackreed** [comment]
Thanks!

**Comment by edsilv** [comment]
@mejackreed I've made my membership public - perhaps you should too? I can see how that might have been confusing.

**Pull request closed without merging**
